# Generated by Django 3.2 on 2025-02-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
    ]
